enum ActionTypes {
    REGISTER = 'REGISTER',
    REGISTER_FAIL = 'REGISTER_FAIL',
    LOGIN = 'ON_LOGIN',
    LOGIN_SUC = 'LOGIN_SUC',
    LOGIN_FAIL = 'LOGIN_FAIL',
    FETCH_TODO = 'FETCH__TODO',
    FETCH_TODO_SUC = 'FETCH_TODO_SUC',
    ADD_TODO = 'ADD_TODO',
    ADD_TODO_SUC = 'ADD_TODO_SUC',
    SEARCH_TODO = 'SEARCH_TODO',
    SEARCH_TODO_SUC = 'SEARCH_TODO_SUC',
    DELETE_TODO = 'DELETE_TODO',
    DELETE_TODO_SUC = 'DELETE_TODO_SUC',
    UPDATE_TODO_CONTENT = 'UPDATE_TODO_CONTENT',
    UPDATE_TODO_CONTENT_SUC = 'UPDATE_TODO_CONTENT_SUC',
    UPDATE_TODO_STATUS = 'UPDATE_TODO_STATUS',
    UPDATE_TODO_STATUS_SUC = 'UPDATE_TODO_STATUS_SUC',
}

export default ActionTypes;
